# version: '3.9'

services:
  db:
    image: postgres:14
    ports:
      - "80:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot_wb:
    # container_name: bot_wb
    build: .
    env_file: .env

    ports:
      - "443:80"

    restart: on-failure

volumes:
  pg_data:

networks:
  postgres:
    driver: bridge
