# version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "80:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: bot-wb
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - db
    restart: on-failure
    volumes:
          - ./logs:/app/logs

volumes:
  pg_data:

networks:
  postgres:
    driver: bridge
